target-version = "py312"
fix = false
line-length = 120

[lint]
select = [
    "E",        # pycodestyle errors
    "W",        # pycodestyle warnings
    "F",        # pyflakes
    "I",        # isort
    "B",        # flake8-bugbear
    "C4",       # flake8-comprehensions
    "UP",       # pyupgrade
    "ANN",      # flake8-annotations
    "T20",      # flake8-print
    "C9",       # mccabe (complexity)
    "N",        # pep8-naming
]

ignore = [
    "E501",     # line-too-long
    "ANN401",   # any-type
    "T201",     # print-found
    "B008",     # do-not-perform-function-calls-in-argument-defaults
    "B006",     # do-not-use-mutable-defaults
    "PLR2004",  # Magic value used in comparison

    # Test Only:
    "B011",     # Do not `assert False`

]

[lint.per-file-ignores]
"_init_.py" = ["F401"]
"tests/*/.py" = ["ANN", "S101", "PLR2004", "N818"]
"tests/*" = ["F401", "F811"]

[lint.isort]
combine-as-imports = true
